[package]
name = "prep-appointments"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4.4"
actix-files = "0.6"
tokio = { version = "1", features = ["full"] }

